name: .NET WinForms CI 🧪

on:
  push:
    branches:
      - master   # 触发构建的分支

env:
  DOTNET_VERSION: '4.8.x'

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 📦
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies 📂
      run: dotnet restore

    - name: Build 🧱
      run: dotnet build --configuration Release

    - name: Publish 🧪
      run: dotnet publish --configuration Release -r win-x64 --output dist
 
    - name: Create archive
      run: |
        cd dist
        tar -zcvf publish.tar.gz *
        cd ..
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: publish
        path: dist/publish.tar.gz